### ISSUE TITLE
Service Intent must be explicit: Intent { act=org.onepf.oms.billing.BIND }

### ISSUE THREAD

**Issue by emperor1412** [onepf/OpenIAB-Unity-Plugin#117]
Hi, today I try latest version of OpenIAB with Unity 5.4.3 and got this bug, any clue to fix this would be appreciated as I'm about to launch my game to SLIDEME and other stores and this is a show-stopper to me.

`12-10 21:24:15.573: W/Unity(25203): UnityPlayerNativeActivity has been deprecated, please update your AndroidManifest to use UnityPlayerActivity instead
12-10 21:24:16.808: D/Unity(25203):  GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_ARM_mali_program_binary
12-10 21:24:21.908: I/Unity(25203): ********** Android OpenIAB plugin initialized **********
12-10 21:24:21.908: I/Unity(25203):  
12-10 21:24:21.908: I/Unity(25203): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
12-10 21:24:26.863: D/OpenIAB-UnityPlugin(25203): createBroadcasts
12-10 21:24:26.863: D/OpenIAB-UnityPlugin(25203): Starting setup.
12-10 21:24:26.913: D/AndroidRuntime(25203): Shutting down VM
12-10 21:24:26.913: E/AndroidRuntime(25203): FATAL EXCEPTION: main
12-10 21:24:26.913: E/AndroidRuntime(25203): Process: com.hoangle.footballevolution, PID: 25203
12-10 21:24:26.913: E/AndroidRuntime(25203): java.lang.Error: FATAL EXCEPTION [main]
12-10 21:24:26.913: E/AndroidRuntime(25203): Unity version     : 5.4.3f1
12-10 21:24:26.913: E/AndroidRuntime(25203): Device model      : samsung SM-N900
12-10 21:24:26.913: E/AndroidRuntime(25203): Device fingerprint: samsung/ha3gxx/ha3g:5.0/LRX21V/N900XXUEBOK2:user/release-keys
12-10 21:24:26.913: E/AndroidRuntime(25203): Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.onepf.oms.billing.BIND }
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:2039)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2147)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at android.app.ContextImpl.bindService(ContextImpl.java:2125)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:559)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at org.onepf.oms.appstore.googleUtils.IabHelper.startSetup(IabHelper.java:277)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at org.onepf.oms.OpenIabHelper$12$1.onIabSetupFinished(OpenIabHelper.java:831)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:920)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at org.onepf.oms.OpenIabHelper.finishSetup(OpenIabHelper.java:889)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at org.onepf.oms.OpenIabHelper.access$1700(OpenIabHelper.java:83)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at org.onepf.oms.OpenIabHelper$12$2.run(OpenIabHelper.java:840)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at android.os.Handler.handleCallback(Handler.java:739)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at android.os.Looper.loop(Looper.java:145)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at java.lang.reflect.Method.invoke(Native Method)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at java.lang.reflect.Method.invoke(Method.java:372)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
12-10 21:24:26.913: E/AndroidRuntime(25203): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
`

**Comment by emperor1412** [comment]
please someone have a look
